export const brandFacts = {
  name: 'AIERXUAN',
  foundedYear: '2014',
  yearsExperience: '10+',
  intelPartnerSince: '2019',
  unitsShipped: '500,000+',
  unitsShippedShort: '500K+',
  countriesServed: '50+',
  globalClients: '500+',
  facilityArea: '15,000㎡',
  productionLines: '6',
  teamMembers: '200+',
  monthlyCapacity: '50,000+',
  monthlyCapacityShort: '50K+',
  moq: '100+',
  moqText: 'MOQ from 100 units',
  sampleQuantityText: 'Samples available from 1-10 units',
  sampleLeadTime: '7-15',
  sampleLeadTimeText: '7-15 days',
  standardProductionLeadTime: '15-25',
  standardProductionLeadTimeText: '15-25 days',
  largeOrderLeadTimeText: '25-45 days',
  rushLeadTimeText: '3-5 days subject to component availability',
  responseTimeText: '24 hours',
  certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001', 'ISO 14001'],
  productCertifications: ['CE', 'FCC', 'RoHS'],
  facilityCertifications: ['ISO 9001', 'ISO 14001'],
  address: {
    streetAddress: 'Juyin Science and Technology Industrial Park, Jihua Street, Longgang District',
    locality: 'Shenzhen',
    region: 'Guangdong',
    countryCode: 'CN',
    countryName: 'China',
    display: 'Juyin Science and Technology Industrial Park, Jihua Street, Longgang District, Shenzhen, China',
    shortDisplay: 'Longgang District, Shenzhen, China',
  },
  contact: {
    phone: '+86 4008-8228-058',
    phoneDisplay: '4008-8228-058',
    email: 'admin@aierxuanlaptop.com',
  },
} as const

export const brandFactText = {
  en: {
    proofLine: `${brandFacts.yearsExperience} Years Experience | Intel Partner Since ${brandFacts.intelPartnerSince} | ${brandFacts.moqText} | ${brandFacts.countriesServed} Countries Served`,
    companySummary: `${brandFacts.name} is a Shenzhen-based OEM/ODM laptop and Mini PC manufacturer founded in ${brandFacts.foundedYear}. The company has shipped ${brandFacts.unitsShipped} units to customers in ${brandFacts.countriesServed} countries.`,
    leadTimeSummary: `Samples: ${brandFacts.sampleLeadTimeText}; standard production: ${brandFacts.standardProductionLeadTimeText}; large orders: ${brandFacts.largeOrderLeadTimeText}.`,
  },
  ru: {
    proofLine: `${brandFacts.yearsExperience} лет опыта | Партнёр Intel с ${brandFacts.intelPartnerSince} | MOQ от 100 единиц | ${brandFacts.countriesServed} стран`,
    companySummary: `${brandFacts.name} — OEM/ODM производитель ноутбуков и мини-ПК из Шэньчжэня, основанный в ${brandFacts.foundedYear} году. Компания поставила ${brandFacts.unitsShipped} устройств клиентам в ${brandFacts.countriesServed} странах.`,
    leadTimeSummary: 'Образцы: 7-15 дней; стандартное производство: 15-25 дней; крупные заказы: 25-45 дней.',
  },
  ja: {
    proofLine: `${brandFacts.yearsExperience}年の経験 | ${brandFacts.intelPartnerSince}年からIntelパートナー | MOQは100台から | ${brandFacts.countriesServed}か国に対応`,
    companySummary: `${brandFacts.name}は${brandFacts.foundedYear}年に設立された深セン拠点のOEM/ODMノートPC・Mini PCメーカーです。${brandFacts.countriesServed}か国の顧客に${brandFacts.unitsShipped}台以上を出荷しています。`,
    leadTimeSummary: `サンプル: ${brandFacts.sampleLeadTimeText}; 標準量産: ${brandFacts.standardProductionLeadTimeText}; 大口注文: ${brandFacts.largeOrderLeadTimeText}.`,
  },
  fr: {
    proofLine: `${brandFacts.yearsExperience} ans d’expérience | Partenaire Intel depuis ${brandFacts.intelPartnerSince} | MOQ à partir de 100 unités | ${brandFacts.countriesServed} pays servis`,
    companySummary: `${brandFacts.name} est un fabricant OEM/ODM de laptops et Mini PC basé à Shenzhen, fondé en ${brandFacts.foundedYear}. L’entreprise a expédié ${brandFacts.unitsShipped} unités à des clients dans ${brandFacts.countriesServed} pays.`,
    leadTimeSummary: `Échantillons: ${brandFacts.sampleLeadTimeText}; production standard: ${brandFacts.standardProductionLeadTimeText}; grandes commandes: ${brandFacts.largeOrderLeadTimeText}.`,
  },
  pt: {
    proofLine: `${brandFacts.yearsExperience} anos de experiência | Parceiro Intel desde ${brandFacts.intelPartnerSince} | MOQ a partir de 100 unidades | ${brandFacts.countriesServed} países atendidos`,
    companySummary: `${brandFacts.name} é uma fabricante OEM/ODM de laptops e Mini PCs sediada em Shenzhen, fundada em ${brandFacts.foundedYear}. A empresa enviou ${brandFacts.unitsShipped} unidades para clientes em ${brandFacts.countriesServed} países.`,
    leadTimeSummary: `Amostras: ${brandFacts.sampleLeadTimeText}; produção padrão: ${brandFacts.standardProductionLeadTimeText}; grandes pedidos: ${brandFacts.largeOrderLeadTimeText}.`,
  },
} as const
